### ISSUE TITLE
Trying to Change Characters errors M+

### ISSUE THREAD

**Issue by wushin** [themanaworld/tmwa#188] opened 2015-12-25 01:14 UTC
Login, you have to wait until you can switch characters first.
Then just try to use M+ to switch to a different character.
M+ errors.

**Comment by wushin** [comment] 2015-12-25 01:15
Login, you have to wait until you can switch characters first.
Then just try to use M+ to switch to a different character.
M+ errors.

**Comment by mekolat** [comment] 2016-01-03 02:54
that's not a bug, it's `prevent_logout` from battle_conf. The main server has it set to 0 so you can always switch char but the test server, for some reason, seems to have it set to 1

**Comment by mekolat** [comment] 2016-01-08 19:22
@wushin close this?

**Closed** 2016-01-08 19:45 UTC
Labels: wontfix
